---
- hosts: localhost
  connection: local
  pre_tasks:
    - community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes

  tasks:
    - name: Homebrew tap
      ansible.builtin.command: brew tap {{ item }}
      with_items:
        - "homebrew/bundle"
        - "homebrew/cask"
        - "homebrew/cask-drivers"
        - "homebrew/cask-fonts"
        - "homebrew/cask-versions"
        - "homebrew/services"
        - "1password/tap"
        - "gbataille/gba"
        - "github/gh"
        - "muesli/tap"
        - "possatti/possatti"

    - name: Homebrew utils
      community.general.homebrew:
        name: {{ item }}
        state: present
        with_items:
          - "act"
          - "antlr"
          - "jpeg"
          - "libpng"
          - "apr-util"
          - "asciinema"
          - "autoconf"
          - "autojump"
          - "automake"
          - "python@3.9"
          - "awscli"
          - "bat"
          - "bfg"
          - "bison"
          - "icu4c"
          - "freetype"
          - "gettext"
          - "libffi"
          - "pkg-config"
          - "zstd"
          - "gd"
          - "krb5"
          - "libzip"
          - "oniguruma"
          - "php"
          - "composer"
          - "ctop"
          - "diff-so-fancy"
          - "docker", link: false
          - "wxwidgets"
          - "exa"
          - "exercism"
          - "fd"
          - "gnutls"
          - "ffmpeg"
          - "flyctl"
          - "fop"
          - "fortune"
          - "fzf"
          - "gh"
          - "git"
          - "glances"
          - "global"
          - "gnupg"
          - "graphviz"
          - "haskell-language-server"
          - "haskell-stack"
          - "htmlq"
          - "httpd"
          - "hugo"
          - "imagemagick"
          - "jenv"
          - "kerl"
          - "lazygit"
          - "libedit"
          - "libiconv"
          - "libxml2"
          - "libxslt"
          - "lima"
          - "litecli"
          - "localstack"
          - "ncdu"
          - "neofetch"
          - "neovim"
          - "nginx"
          - "php@7.4"
          - "pinentry-mac"
          - "postgresql", restart_service: true
          - "python-tk@3.9"
          - "rabbitmq", restart_service: true
          - "re2c"
          - "ripgrep"
          - "rlwrap"
          - "ruby"
          - "shellcheck"
          - "svn"
          - "terraform"
          - "tokei"
          - "trash"
          - "tre-command"
          - "tree"
          - "vim"
          - "wget"
          - "wireguard-tools"
          - "youtube-dl"
          - "zlib"
          - "zsh"
          - "zsh-autosuggestions"
          - "zsh-history-substring-search"
          - "zsh-syntax-highlighting"
          - "gbataille/gba/githud"
          - "muesli/tap/duf"
          - "possatti/possatti/pokemonsay"


    - name: Homebrew casks
      community.general.homebrew:
        name: {{ item }}
        state: present
        with_items:
         -  "1password"
         -  "1password-cli"
         -  "alfred"
         -  "anki"
         -  "audacity"
         -  "calibre"
         -  "charles"
         -  "contexts"
         -  "daisydisk"
         -  "dash"
         -  "deckset"
         -  "deepl"
         -  "discord"
         -  "docker"
         -  "dotnet-sdk"
         -  "dropbox"
         -  "firefox"
         -  "font-baskervville"
         -  "font-bitstream-vera-sans-mono-nerd-font"
         -  "font-cormorant-garamond"
         -  "font-fantasque-sans-mono"
         -  "font-hasklig"
         -  "font-libre-baskerville"
         -  "font-sauce-code-pro-nerd-font"
         -  "font-source-code-pro"
         -  "font-source-han-mono"
         -  "font-source-han-noto-cjk"
         -  "font-source-han-sans"
         -  "font-source-han-serif"
         -  "google-chrome"
         -  "google-cloud-sdk"
         -  "google-drive"
         -  "hook"
         -  "insomnia"
         -  "iterm2"
         -  "jetbrains-toolbox"
         -  "kaleidoscope"
         -  "kodi"
         -  "ledger-live"
         -  "logitech-options"
         -  "logitech-presentation"
         -  "luxmark"
         -  "mactex"
         -  "mark-text"
         -  "microsoft-auto-update"
         -  "microsoft-edge"
         -  "multipass"
         -  "musescore"
         -  "obsidian"
         -  "onedrive"
         -  "owasp-zap"
         -  "pdf-expert"
         -  "postman"
         -  "qview"
         -  "sketch"
         -  "skype"
         -  "sourcetree"
         -  "spotify"
         -  "squirrel"
         -  "steam"
         -  "transmission"
         -  "visual-studio-code"
         -  "vlc"
         -  "welly"
         -  "wkhtmltopdf"
         -  "xld"
