---
- hosts: localhost
  connection: local
  pre_tasks:
    - community.general.homebrew:
        update_homebrew: yes
        upgrade_all: yes

  tasks:
    - name: Generate an OpenSSH keypair
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa
        type: ed25519
        passphrase:  {{ vault.ssh-key-passphrase }}

    - name: Homebrew tap
      ansible.builtin.command: brew tap {{ item }}
      with_items:
        - "homebrew/bundle"
        - "homebrew/cask"
        - "homebrew/cask-drivers"
        - "homebrew/cask-fonts"
        - "homebrew/cask-versions"
        - "homebrew/services"
        - "1password/tap"
        - "gbataille/gba"
        - "github/gh"
        - "muesli/tap"
        - "possatti/possatti"

    - name: Homebrew utils
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_items:
      - "act"
      - "antlr"
      - "jpeg"
      - "libpng"
      - "apr-util"
      - "asciinema"
      - "autoconf"
      - "autojump"
      - "automake"
      - "python@3.9"
      - "awscli"
      - "bat"
      - "bfg"
      - "bison"
      - "icu4c"
      - "freetype"
      - "gettext"
      - "libffi"
      - "pkg-config"
      - "zstd"
      - "gd"
      - "krb5"
      - "libzip"
      - "oniguruma"
      - "php"
      - "composer"
      - "ctop"
      - "diff-so-fancy"
      - "docker"
      - "wxwidgets"
      - "exa"
      - "exercism"
      - "fd"
      - "gnutls"
      - "ffmpeg"
      - "flyctl"
      - "fop"
      - "fortune"
      - "fzf"
      - "gh"
      - "git"
      - "glances"
      - "global"
      - "gnupg"
      - "graphviz"
      - "haskell-language-server"
      - "haskell-stack"
      - "htmlq"
      - "httpd"
      - "hugo"
      - "imagemagick"
      - "jenv"
      - "kerl"
      - "lazygit"
      - "libedit"
      - "libiconv"
      - "libxml2"
      - "libxslt"
      - "lima"
      - "litecli"
      - "localstack"
      - "ncdu"
      - "neofetch"
      - "neovim"
      - "nginx"
      - "php@7.4"
      - "pinentry-mac"
      - "postgresql"
      - "python-tk@3.9"
      - "rabbitmq"
      - "re2c"
      - "ripgrep"
      - "rlwrap"
      - "ruby"
      - "shellcheck"
      - "svn"
      - "terraform"
      - "tokei"
      - "trash"
      - "tre-command"
      - "tree"
      - "vim"
      - "wget"
      - "wireguard-tools"
      - "youtube-dl"
      - "zlib"
      - "zsh"
      - "zsh-autosuggestions"
      - "zsh-history-substring-search"
      - "zsh-syntax-highlighting"
      - "muesli/tap/duf"
      - "possatti/possatti/pokemonsay"
      -  "homebrew/cask/1password"
      -  "homebrew/cask/1password-cli"
      -  "homebrew/cask/alfred"
      -  "homebrew/cask/anki"
      -  "homebrew/cask/audacity"
      -  "homebrew/cask/calibre"
      -  "homebrew/cask/charles"
      -  "homebrew/cask/contexts"
      -  "homebrew/cask/daisydisk"
      -  "homebrew/cask/dash"
      -  "homebrew/cask/deckset"
      -  "homebrew/cask/deepl"
      -  "homebrew/cask/discord"
      -  "homebrew/cask/docker"
      -  "homebrew/cask/dotnet-sdk"
      -  "homebrew/cask/dropbox"
      -  "homebrew/cask/firefox"
      -  "homebrew/cask/google-chrome"
      -  "homebrew/cask/google-cloud-sdk"
      -  "homebrew/cask/google-drive"
      -  "homebrew/cask/hook"
      -  "homebrew/cask/insomnia"
      -  "homebrew/cask/iterm2"
      -  "homebrew/cask/jetbrains-toolbox"
      -  "homebrew/cask/kaleidoscope"
      -  "homebrew/cask/kodi"
      -  "homebrew/cask/ledger-live"
      -  "homebrew/cask/logitech-options"
      -  "homebrew/cask/logitech-presentation"
      -  "homebrew/cask/luxmark"
      -  "homebrew/cask/mactex"
      -  "homebrew/cask/mark-text"
      -  "homebrew/cask/microsoft-auto-update"
      -  "homebrew/cask/microsoft-edge"
      -  "homebrew/cask/multipass"
      -  "homebrew/cask/musescore"
      -  "homebrew/cask/obsidian"
      -  "homebrew/cask/onedrive"
      -  "homebrew/cask/owasp-zap"
      -  "homebrew/cask/pdf-expert"
      -  "homebrew/cask/postman"
      -  "homebrew/cask/qview"
      -  "homebrew/cask/sketch"
      -  "homebrew/cask/skype"
      -  "homebrew/cask/sourcetree"
      -  "homebrew/cask/spotify"
      -  "homebrew/cask/squirrel"
      -  "homebrew/cask/steam"
      -  "homebrew/cask/transmission"
      -  "homebrew/cask/visual-studio-code"
      -  "homebrew/cask/vlc"
      -  "homebrew/cask/welly"
      -  "homebrew/cask/wkhtmltopdf"
      -  "homebrew/cask/xld"
      -  "homebrew/cask-fonts/font-baskervville"
      -  "homebrew/cask-fonts/font-bitstream-vera-sans-mono-nerd-font"
      -  "homebrew/cask-fonts/font-cormorant-garamond"
      -  "homebrew/cask-fonts/font-fantasque-sans-mono"
      -  "homebrew/cask-fonts/font-hasklig"
      -  "homebrew/cask-fonts/font-libre-baskerville"
      -  "homebrew/cask-fonts/font-sauce-code-pro-nerd-font"
      -  "homebrew/cask-fonts/font-source-code-pro"
      -  "homebrew/cask-fonts/font-source-han-mono"
      -  "homebrew/cask-fonts/font-source-han-noto-cjk"
      -  "homebrew/cask-fonts/font-source-han-sans"
      -  "homebrew/cask-fonts/font-source-han-serif"
